services:
  governance_core:
    image: ghcr.io/ilkerkaanipcioglu/governance-core:latest
    container_name: govcore
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - govcore_data:/opt/app/data
    networks:
      - proxy-network
      - internal-network

  kadro_platform:
    image: ghcr.io/ilkerkaanipcioglu/kadro-platform:latest
    container_name: kadro
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - kadro_data:/app/data
    networks:
      - proxy-network
      - internal-network

networks:
  proxy-network:
    external: true
  internal-network:
    external: true

volumes:
  govcore_data:
  kadro_data:
